### ISSUE TITLE
Got error when run in tensorflow 1.2

### ISSUE THREAD

**Issue by Qoboty** [santi-pdp/segan#20]
I download the weight and run the code "clean_wav.sh" like this
`sh clean_wav.sh test/16k_p232_052.wav ./`
my tensorflow is 1.2.0

 I got error as below,How to fix it?

Not clipping D weights
Traceback (most recent call last):
  File "main.py", line 122, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 89, in main
    se_model = SEGAN(sess, FLAGS, udevices)
  File "/mnt/tensorflowShare/segan-master/model.py", line 118, in __init__
    self.build_model(args)
  File "/mnt/tensorflowShare/segan-master/model.py", line 144, in build_model
    self.d_opt = d_opt.apply_gradients(avg_d_grads)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 446, in apply_gradients
    self._create_slots([_get_variable_for(v) for v in var_list])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/rmsprop.py", line 100, in _create_slots
    v.dtype, "rms", self._name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 749, in _get_or_make_slot_with_initializer
    var, initializer, shape, dtype, op_name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/slot_creator.py", line 146, in create_slot_with_initializer
    dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/slot_creator.py", line 66, in _create_slot_var
    validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 367, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 682, in _get_single_variable
    "VarScope?" % name)
ValueError: Variable d_model/d_block_2/d_vbn_2/gamma/RMSProp/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

**Comment by gmkim90** [comment]
I got the same error. 
Do you have any modifications or progress on this issue?

**Comment by santi-pdp** [comment]
Hi guys,

note that the TF version of the project is 0.12, not 1.X . The solutions are: 1) use a virtualenv with Tensorflow 0.12 version or 2) upgrade the parts of the code that conflict with the new API. I am quite busy now with other projects, so I'll have a look when I have a free slot. Thanks for your interest!

**Comment by YeBobr** [comment]
I got the same error,too.
Someone have solved it?
My TF version is 1.3.0.

**Comment by rafaelvalle** [comment]
Following @santi-pdp recommendation, I was able to have it work with tensorflow 0.12.
Nonetheless, it would be good if someone is able to have it working with tensorflow 0.13

**Comment by GaofengCheng** [comment]
@rafaelvalle how long will it take to finish the whole training if i have 4 k80 gpu cores available:) ?

**Comment by rafaelvalle** [comment]
I think they have that information on the packet paper

**Comment by linan2** [comment]
Have you solve this problem? I have the same problem but I don't know how to solve it.

**Comment by rafaelvalle** [comment]
@linan2 look at my Oct 16 message.

**Comment by gowthamcastro** [comment]
use tensorflow within environment and have tensorflow updated version i have error but i already clear it

**Comment by tiankong-hut** [comment]
add " with tf.variable_scope(tf.get_variable_scope(), reuse=False): " before (in model.py)
                self.d_opt = d_opt.apply_gradients(avg_d_grads)   
                self.g_opt = g_opt.apply_gradients(avg_g_grads)
and run in python 3.4   ,tensorflow 1.0.0

**Comment by fcakyon** [comment]
I have updated this repo for tensorflow>1.0 and python>3.5: https://github.com/fcakyon/segan
@ghost @linan2 @YeBobr @lifelongeek @Qoboty
