### ISSUE TITLE
Loading model and prediction: error 

### ISSUE THREAD

**Issue by arijit17** [santi-pdp/segan#43]
Hi!

I'm using this fork: https://github.com/lordet01/segan
and Python 3.5 and latest TensorFlow. And the training runs nicely. 

Then, I downloaded the model from here:
http://veu.talp.cat/segan/release_weights/segan_v1.1.tar.gz

Then running the script:
https://github.com/santi-pdp/segan/blob/master/clean_wav.sh

Gives error:
```
(C:\Users\abisw\AppData\Local\Continuum\Anaconda3) C:\GIT\segan>python main.py --init_noise_std 0. --save_path segan_v1.1 --batch_size 100 --g_nl prelu --weights SEGAN-41700 --preemph 0.95 --bias_deconv True --bias_downconv True --bias_D_conv True --test_wav p226_004.wav --clean_save_path C:\GIT\segan\out
2018-03-27 17:08:00.018857: I C:\tf_jenkins\workspace\rel-win\M\windows\PY\35\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Parsed arguments:  {'d_learning_rate': <absl.flags._flag.Flag object at 0x0000020A41A3C4E0>, 'helpshort': <tensorflow.python.platform.app._HelpshortFlag object at 0x0000020A41A3C908>, 'denoise_lbound': <absl.flags._flag.Flag object at 0x0000020A41A35D30>, 'd_label_smooth': <absl.flags._flag.Flag object at 0x0000020A41A35E80>, 'beta_1': <absl.flags._flag.Flag object at 0x0000020A41A3C550>, 'save_clean_path': <absl.flags._flag.Flag object at 0x0000020A41A3C6D8>, 'helpfull': <tensorflow.python.platform.app._HelpfullFlag object at 0x0000020A41A3C898>, 'init_l1_weight': <absl.flags._flag.Flag object at 0x0000020A41A35FD0>, 'batch_size': <absl.flags._flag.Flag object at 0x0000020A41A359B0>, 'e2e_dataset': <absl.flags._flag.Flag object at 0x0000020A41A3C668>, 'g_nl': <absl.flags._flag.Flag object at 0x0000020A41A3C278>, 'seed': <absl.flags._flag.Flag object at 0x0000020A41A35860>, 'canvas_size': <absl.flags._flag.Flag object at 0x0000020A41A35B00>, 'z_depth': <absl.flags._flag.Flag object at 0x0000020A41A3C160>, 'noise_decay': <absl.flags._flag.Flag object at 0x0000020A41A35DD8>, 'save_path': <absl.flags._flag.Flag object at 0x0000020A41A3C208>, 'g_type': <absl.flags._flag.Flag object at 0x0000020A41A3C3C8>, 'z_dim': <absl.flags._flag.Flag object at 0x0000020A41A3C0B8>, 'save_freq': <absl.flags._flag.Flag object at 0x0000020A41A35A58>, 'l1_remove_epoch': <absl.flags._flag.Flag object at 0x0000020A41A35C50>, 'init_noise_std': <absl.flags._flag.Flag object at 0x0000020A41A35F28>, 'test_wav': <absl.flags._flag.Flag object at 0x0000020A41A3C748>, 'weights': <absl.flags._flag.Flag object at 0x0000020A41A3C7B8>, 'epoch': <absl.flags._flag.Flag object at 0x0000020A41A35908>, 'model': <absl.flags._flag.Flag object at 0x0000020A41A3C320>, 'synthesis_path': <absl.flags._flag.Flag object at 0x0000020A41A3C5F8>, 'h': <tensorflow.python.platform.app._HelpFlag object at 0x0000020A41A3C7F0>, 'denoise_epoch': <absl.flags._flag.Flag object at 0x0000020A41A35BA8>, 'g_learning_rate': <absl.flags._flag.Flag object at 0x0000020A41A3C470>, 'help': <tensorflow.python.platform.app._HelpFlag object at 0x0000020A41A3C7F0>}
Using device:  /device:CPU:0
Creating GAN model
*** Building Generator ***
Downconv (100, 16384, 1) -> (100, 8192, 16)
Adding skip connection downconv 0
-- Enc: prelu activation --
Downconv (100, 8192, 16) -> (100, 4096, 32)
Adding skip connection downconv 1
-- Enc: prelu activation --
Downconv (100, 4096, 32) -> (100, 2048, 32)
Adding skip connection downconv 2
-- Enc: prelu activation --
Downconv (100, 2048, 32) -> (100, 1024, 64)
Adding skip connection downconv 3
-- Enc: prelu activation --
Downconv (100, 1024, 64) -> (100, 512, 64)
Adding skip connection downconv 4
-- Enc: prelu activation --
Downconv (100, 512, 64) -> (100, 256, 128)
Adding skip connection downconv 5
-- Enc: prelu activation --
Downconv (100, 256, 128) -> (100, 128, 128)
Adding skip connection downconv 6
-- Enc: prelu activation --
Downconv (100, 128, 128) -> (100, 64, 256)
Adding skip connection downconv 7
-- Enc: prelu activation --
Downconv (100, 64, 256) -> (100, 32, 256)
Adding skip connection downconv 8
-- Enc: prelu activation --
Downconv (100, 32, 256) -> (100, 16, 512)
Adding skip connection downconv 9
-- Enc: prelu activation --
Downconv (100, 16, 512) -> (100, 8, 1024)
-- Enc: prelu activation --
g_dec_depths:  [512, 256, 256, 128, 128, 64, 64, 32, 32, 16, 1]
Deconv (100, 8, 2048) -> (100, 16, 512)
-- Dec: prelu activation --
Fusing skip connection of shape (100, 16, 512)
Deconv (100, 16, 1024) -> (100, 32, 256)
-- Dec: prelu activation --
Fusing skip connection of shape (100, 32, 256)
Deconv (100, 32, 512) -> (100, 64, 256)
-- Dec: prelu activation --
Fusing skip connection of shape (100, 64, 256)
Deconv (100, 64, 512) -> (100, 128, 128)
-- Dec: prelu activation --
Fusing skip connection of shape (100, 128, 128)
Deconv (100, 128, 256) -> (100, 256, 128)
-- Dec: prelu activation --
Fusing skip connection of shape (100, 256, 128)
Deconv (100, 256, 256) -> (100, 512, 64)
-- Dec: prelu activation --
Fusing skip connection of shape (100, 512, 64)
Deconv (100, 512, 128) -> (100, 1024, 64)
-- Dec: prelu activation --
Fusing skip connection of shape (100, 1024, 64)
Deconv (100, 1024, 128) -> (100, 2048, 32)
-- Dec: prelu activation --
Fusing skip connection of shape (100, 2048, 32)
Deconv (100, 2048, 64) -> (100, 4096, 32)
-- Dec: prelu activation --
Fusing skip connection of shape (100, 4096, 32)
Deconv (100, 4096, 64) -> (100, 8192, 16)
-- Dec: prelu activation --
Fusing skip connection of shape (100, 8192, 16)
Deconv (100, 8192, 32) -> (100, 16384, 1)
-- Dec: tanh activation --
Amount of alpha vectors:  21
Amount of skip connections:  10
Last wave shape:  (100, 16384, 1)
*************************
num of G returned:  23
*** Discriminator summary ***
WARNING:tensorflow:From C:\GIT\segan\bnorm.py:22: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
D block 0 input shape: (100, 16384, 2) *** downconved shape: (100, 8192, 16)  *** Applying VBN *** Applying Lrelu ***
D block 1 input shape: (100, 8192, 16) *** downconved shape: (100, 4096, 32)  *** Applying VBN *** Applying Lrelu ***
D block 2 input shape: (100, 4096, 32) *** downconved shape: (100, 2048, 32)  *** Applying VBN *** Applying Lrelu ***
D block 3 input shape: (100, 2048, 32) *** downconved shape: (100, 1024, 64)  *** Applying VBN *** Applying Lrelu ***
D block 4 input shape: (100, 1024, 64) *** downconved shape: (100, 512, 64)  *** Applying VBN *** Applying Lrelu ***
D block 5 input shape: (100, 512, 64) *** downconved shape: (100, 256, 128)  *** Applying VBN *** Applying Lrelu ***
D block 6 input shape: (100, 256, 128) *** downconved shape: (100, 128, 128)  *** Applying VBN *** Applying Lrelu ***
D block 7 input shape: (100, 128, 128) *** downconved shape: (100, 64, 256)  *** Applying VBN *** Applying Lrelu ***
D block 8 input shape: (100, 64, 256) *** downconved shape: (100, 32, 256)  *** Applying VBN *** Applying Lrelu ***
D block 9 input shape: (100, 32, 256) *** downconved shape: (100, 16, 512)  *** Applying VBN *** Applying Lrelu ***
D block 10 input shape: (100, 16, 512) *** downconved shape: (100, 8, 1024)  *** Applying VBN *** Applying Lrelu ***
discriminator deconved shape:  (100, 8, 1024)
discriminator output shape:  (100, 1)
*****************************
Not clipping D weights
Loading model weights...
[*] Reading checkpoints...
2018-03-27 17:08:24.006124: W C:\tf_jenkins\workspace\rel-win\M\windows\PY\35\tensorflow\core\framework\op_kernel.cc:1202] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key beta1_power not found in checkpoint
Traceback (most recent call last):
  File "C:\Users\abisw\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1361, in _do_call
    return fn(*args)
  File "C:\Users\abisw\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _run_fn
    target_list, status, run_metadata)
  File "C:\Users\abisw\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Key beta1_power not found in checkpoint
         [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 104, in <module>
    tf.app.run()
  File "C:\Users\abisw\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "main.py", line 87, in main
    se_model.load(FLAGS.save_path, FLAGS.weights)
  File "C:\GIT\segan\model.py", line 46, in load
    self.saver.restore(self.sess, os.path.join(save_path, ckpt_name))
  File "C:\Users\abisw\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1755, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\Users\abisw\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 905, in run
    run_metadata_ptr)
  File "C:\Users\abisw\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\abisw\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1355, in _do_run
    options, run_metadata)
  File "C:\Users\abisw\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key beta1_power not found in checkpoint
         [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op 'save/RestoreV2', defined at:
  File "main.py", line 104, in <module>
    tf.app.run()
  File "C:\Users\abisw\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "main.py", line 87, in main
    se_model.load(FLAGS.save_path, FLAGS.weights)
  File "C:\GIT\segan\model.py", line 45, in load
    self.saver = tf.train.Saver()
  File "C:\Users\abisw\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1293, in __init__
    self.build()
  File "C:\Users\abisw\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1302, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Users\abisw\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1339, in _build
    build_save=build_save, build_restore=build_restore)
  File "C:\Users\abisw\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 796, in _build_internal
    restore_sequentially, reshape)
  File "C:\Users\abisw\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 449, in _AddRestoreOps
    restore_sequentially)
  File "C:\Users\abisw\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 847, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "C:\Users\abisw\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1113, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "C:\Users\abisw\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\abisw\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3271, in create_op
    op_def=op_def)
  File "C:\Users\abisw\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Key beta1_power not found in checkpoint
         [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
```

**Comment by akash9182** [comment]
Did you find a solution to this error?

**Comment by Michaellee955** [comment]
Same problem, have you solved it?

**Comment by Michaellee955** [comment]
Well, I gave up Tensorflow version 1.* and went back to 0.12.1 and all worked well. Seems some incompatibility between fork code and original code.
