### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: No registered 'TemporaryVariable' OpKernel for 'XLA_GPU' devices compatible with node {{node device_2/gradients/AddN_23/tmp_var}}

### ISSUE THREAD

**Issue by zcy618** [santi-pdp/segan#82]
Dear friend:
I am using tensorflow-gpu 1.15.2 version, but I meet below issue when I start to train, could you help to check it please?

2020-10-10 12:09:16.575896: W tensorflow/core/kernels/queue_base.cc:277] _3_device_1/wav_and_noisy/random_shuffle_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "/home/chenyuz/Desktop/segan/segen_env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/chenyuz/Desktop/segan/segen_env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/chenyuz/Desktop/segan/segen_env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: No registered 'TemporaryVariable' OpKernel for 'XLA_GPU' devices compatible with node {{node device_2/gradients/AddN_23/tmp_var}}
	.  Registered:  device='GPU'; dtype in [DT_INT64]
  device='GPU'; dtype in [DT_DOUBLE]
  device='GPU'; dtype in [DT_FLOAT]
  device='GPU'; dtype in [DT_HALF]
  device='CPU'

	 [[device_2/gradients/AddN_23/tmp_var]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 122, in <module>
    tf.app.run()
  File "/home/chenyuz/Desktop/segan/segen_env/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/chenyuz/Desktop/segan/segen_env/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/chenyuz/Desktop/segan/segen_env/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "main.py", line 96, in main
    se_model.train(FLAGS, udevices)
  File "/home/chenyuz/Desktop/segan/model.py", line 412, in train
    self.d_rl_losses[0]])
  File "/home/chenyuz/Desktop/segan/segen_env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/chenyuz/Desktop/segan/segen_env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/chenyuz/Desktop/segan/segen_env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/chenyuz/Desktop/segan/segen_env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: No registered 'TemporaryVariable' OpKernel for 'XLA_GPU' devices compatible with node {{node device_2/gradients/AddN_23/tmp_var}}
	.  Registered:  device='GPU'; dtype in [DT_INT64]
  device='GPU'; dtype in [DT_DOUBLE]
  device='GPU'; dtype in [DT_FLOAT]
  device='GPU'; dtype in [DT_HALF]
  device='CPU'

	 [[device_2/gradients/AddN_23/tmp_var]]

**Comment by ablzzz** [comment]
I got the exact same issue. 
tensorflow.python.framework.errors_impl.NotFoundError: No registered 'TemporaryVariable' OpKernel for 'XLA_CPU' devices compatible with node {{node device_1/gradients/AddN_23/tmp_var}}
        .  Registered:  device='GPU'; dtype in [DT_INT64]
  device='GPU'; dtype in [DT_DOUBLE]
  device='GPU'; dtype in [DT_FLOAT]
  device='GPU'; dtype in [DT_HALF]
  device='CPU'

         [[device_1/gradients/AddN_23/tmp_var]]
